version: "3.4"

services:
  mongo:
    container_name: mongo
    image: mongo:3.7
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql

  postgre:
    container_name: postgre
    image: postgres:11.7
    ports:
      - 5432:5432
    volumes:
      - postgre:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 2s
      retries: 10

volumes:
  mongo:
  mysql:
  postgre:
